import mongoose from 'mongoose';

const sessionSchema = new mongoose.Schema({
  token: { type: String, required: true },
  deviceInfo: {
    browser: String,
    os: String,
    device: String,
  },
  ipAddress: String,
  location: String,
  loginTime: { type: Date, default: Date.now },
  lastActivity: { type: Date, default: Date.now },
  isActive: { type: Boolean, default: true },
});

export const teacherSchema = new mongoose.Schema({
  firstName: String,
  lastName: String,
  email: { type: String, unique: true, required: true },
  ratePerClass: Number,
  password: String,
  continent: {
    type: String,
    enum: ['Africa', 'Europe', 'Asia', 'Americas', 'Oceania'],
    required: true,
  },
  phone: { type: String, default: '' },
  country: { type: String, default: '' },
  googleMeetLink: { type: String, default: '' },
  timezone: { type: String, default: '' },
  bio: { type: String, default: '' },
  yearsOfExperience: { type: Number, default: 0 },
  specializations: { type: [String], default: [] },
  certifications: { type: [String], default: [] },
  showScheduleToStudents: { type: Boolean, default: true },
  status: {
    type: String,
    enum: ['pending', 'active', 'suspended'],
    default: 'pending',
  },
  inviteToken: String,
  inviteExpires: Date,
  active: { type: Boolean, default: false },
  lessonsCompleted: { type: Number, default: 0 },
  earned: { type: Number, default: 0 },
  resetPasswordToken: String,
  resetPasswordExpires: Date,
  lastPasswordChange: Date,
  sessions: [sessionSchema],
  lastLogin: Date,
  twoFactorEnabled: { type: Boolean, default: false },
  twoFactorSecret: String,
  twoFactorBackupCodes: [String],
  twoFactorVerified: { type: Boolean, default: false },
  pushSubscription: { type: Object, default: null },
  scheduledDeletionAt: { type: Date, default: null },
  deletionWarningEmailSent: { type: Boolean, default: false },
  photo:       { type: String, default: "" },
  displayName: { type: String, default: "" },
  bankName:      { type: String, default: "" },
  accountNumber: { type: String, default: "" },
  accountName:   { type: String, default: "" },
}, { timestamps: true });
